version: '3'
services:
  kibana:
    image: kibana:7.10.1
    ports:
      - "5601:5601"
  elasticsearch:
    image: elasticsearch:7.10.1
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
